language: node_js
node_js:
  - "8"
  - "9"
dependencies:
  override:
    - npm install
script:
  - npm run style  
  - npm test
deploy:
  provider: npm
  email: alexeykolpino@gmail.com
  api_key: $NPM_TOKEN
  on:
    tags: true